### PR TITLE
[Internal] Pre-Checkin Tests: Fixes Failing Tests After Emulator Refresh; Marks Failing Encryption Test as Ignore

### PR DESCRIPTION
**Pull request by akotalwar**
# Pull Request Template

## Description

With the release of the new emulator, pre-checkin tests are failing due to mismatch in expected output.
Following tests are fixed in this PR:

[Query]
TestQueriesWithPartitionKeyNone
TestPassingOptimisticDirectExecutionQueries
IndexUtilizationHeaderLengthTest
IndexUtilizationParse
TestQueryPlanGatewayAndServiceInteropAsync

[SDK]
ChangeFeedIteratorCore_WithFullFidelityReadFromBeginning

Apart from above, this change also marks following test as Ignore since it's flaky and repeatedly fails in cloudtest runs:
[Encryption]
EncryptionChangeFeedDecryptionSuccessful

Thanks to Philip for guidance on SDK owned test and Sourabh for engaging and informing the correct teams.

## Type of change

Please delete options that are not relevant.

- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

## Closing issues

To automatically close an issue: closes #IssueNumber

### CODE REVIEW

**Review by adityasa — DISMISSED** [review]
:shipit:

**Comment by adityasa** [comment]
I would be tempted to include Index Utilization tests as part of this as well.

**Comment by adityasa** [comment]
@leminh98 as FYI.

---
In reply to: [1905057901](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/4271#issuecomment-1905057901) [](http://example.com/codeflow?ancestors=1905057901)

**Review by neildsh — APPROVED** [review]
:shipit:

**Review by philipthomas-MSFT — DISMISSED** [review]

**Review by leminh98 — DISMISSED** [review]

**Comment by kirankumarkolli** [comment]
@akotalwar is the regression with new emulator even with-out ODE? 
If so, then let's update emulator team and get it reverted. It will impact external CX also, right?

**Comment by adityasa** [comment]
@kirankumarkolli this is a test only fix. This is not a regression in Emulator (or product code), but rather the tests were stale.

**Review by adityasa — APPROVED** [review]
:shipit:

**Review by kirankumarkolli — APPROVED** [review]

**Comment by sourabh1007** [comment]
> @akotalwar is the regression with new emulator even with-out ODE? If so, then let's update emulator team and get it reverted. It will impact external CX also, right?

@v1k1 from Emulator team, already reported these Test failures, before releasing the emulator.

**Pull request merged**
