### PR TITLE
Distributed Tracing: Update operation name for non-generic feed iterator read operation

### PR DESCRIPTION
**Pull request by joegoldman2**
## Description

Update operation name for non-generic feed iterator to align with the generic version:

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/75a2e5f98af8b9c11c621e052cb5761c3d15aaf3/Microsoft.Azure.Cosmos/src/Resource/FeedIterators/FeedIteratorInlineCore%7BT%7D.cs#L50-L50

## Type of change

Please delete options that are not relevant.

- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

### CODE REVIEW

**Review by FabianMeiswinkel — APPROVED** [review]
LGTM

**Review by kirankumarkolli — APPROVED** [review]

**Comment by joegoldman2** [comment]
Failure in CI seems unrelated.

**Pull request merged**
