### PR TITLE
Region Availability: Adds New Zealand North region for Public Usage.

### LINKED ISSUE #4519: Add New Zealand North region in Public Contract

### PR DESCRIPTION
**Pull request by hdornadula**
# Pull Request Template

## Description

This PR makes the New Zealand North region available for public usage.

## Type of change

Please delete options that are not relevant.

- [] New feature (non-breaking change which adds functionality)

## Closing issues

To automatically close an issue: closes #4519

### CODE REVIEW

**Comment by hdornadula** [comment]
I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term "You" includes me and my employer.

@microsoft-github-policy-service agree company="Microsoft"

**Comment by kirankumarkolli** [comment]
@hdornadula it seems full JSON file is updated (may be newline carriage return issues).
Its very hard to reason what the changes are (for future tracking).
Can you please take a look and see if the changes can be scoped to the min required.

**Review by kirankumarkolli — APPROVED** [review]

**Review by FabianMeiswinkel — APPROVED** [review]
LGTM

**Pull request merged**
