### PR TITLE
Documentation: Fixes ItemRequestOptions to use items instead of document for Triggers

### LINKED ISSUE #2591: Cosmos: Issue with the documentation
It mentions in the Remarks as
`Only valid when used with Create, Replace and Delete methods for documents. `
But its valid for **_items_** as well and not only documents. Also it says
`Currently only one PreTrigger is permitted per operation.`
while the page is for **_PostTrigger_**.

Feel free to correct if my understanding is wrong.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a375826-f3b5-3a59-ce12-d27ad10c50d0
* Version Independent ID: 0f1c6162-6011-a6de-b1c4-a5299f6e56b6
* Content: [ItemRequestOptions.PostTriggers Property (Microsoft.Azure.Cosmos) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.itemrequestoptions.posttriggers?view=azure-dotnet#feedback)
* Content Source: [xml/Microsoft.Azure.Cosmos/ItemRequestOptions.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Cosmos/ItemRequestOptions.xml)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

### PR DESCRIPTION
**Pull request by Venkat1340**
# Pull Request Template

## Description

Fixes error in trigger documentation.

## Type of change

Please delete options that are not relevant.

- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

## Closing issues

To automatically close an issue: closes #2591

### CODE REVIEW

**Review by j82w — APPROVED** [review]

**Comment by j82w** [comment]
@Venkat since you are a member of Azure can you please clone the repository directly instead of using a fork. The gates have to be manually triggered for forks because of security reasons. If you create a branch it will run automatically.

**Comment by Venkat1340** [comment]
# sign off

**Pull request merged**
