### PR TITLE
Azure.Cosmos.Operation => Azure-Cosmos-Operation-Request-Diagnostics

### PR DESCRIPTION
**Pull request by joegoldman2**

### CODE REVIEW

**Review by kirankumarkolli — APPROVED** [review]

**Comment by Pilchie** [comment]
Do we need to update [Aspire](https://github.com/search?q=repo%3Adotnet%2Faspire%20Azure.Cosmos.Operation&type=code) as well?

**Comment by joegoldman2** [comment]
> Do we need to update [Aspire](https://github.com/search?q=repo%3Adotnet%2Faspire%20Azure.Cosmos.Operation&type=code) as well?

No, `Azure.Cosmos.Operation` is still the name of the Activity Source and `Azure-Cosmos-Operation-Request-Diagnostics` of the Event Source. I just changed a comment in this PR.

**Comment by joegoldman2** [comment]
> Do we need to update [Aspire](https://github.com/search?q=repo%3Adotnet%2Faspire%20Azure.Cosmos.Operation&type=code) as well?

No, `Azure.Cosmos.Operation` is still the name of the Activity Source and `Azure-Cosmos-Operation-Request-Diagnostics` for the Event Source. I just changed a comment in this PR.

**Pull request merged**
