### PR TITLE
CosmosClientBuilder: Adds overload for passing TokenCredential

### LINKED ISSUE #2749: Add `TokenCredential` builder method to `CosmosClientBuilder`
**Is your feature request related to a problem? Please describe.**
Cannot find how to pass `TokenCredential` instance to `CosmosClientBuilder`

**Describe the solution you'd like**
Include a builder method for passing a `TokenCredential` to the `CosmosClientBuilder` chain.

**Describe alternatives you've considered**
Creating `CosmosClient` directly and passing `TokenCredential` during the instantiation

**Additional context**
Java SDK has a [`credential` method in their `CosmosClientBuilder`](https://docs.microsoft.com/en-us/java/api/com.azure.cosmos.cosmosclientbuilder.credential?view=azure-java-stable)

### PR DESCRIPTION
**Pull request by levimatheri**
## Description

Adds constructor to `CosmosClientBuilder` for using a `TokenCredential` instance, e.g. `DefaultAzureCredential`.

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update (addition)

## Closing issues

Closes #2749

### CODE REVIEW

**Comment by ealsur** [comment]
@levimatheri please run https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/UpdateContracts.ps1 on your branch to generate the changes in the API surface

**Review by ealsur — APPROVED** [review]

**Review by kirankumarkolli — APPROVED** [review]

**Comment by ealsur** [comment]
Thanks @levimatheri for your contribution!

**Pull request merged**
