### PR TITLE
Request Charge: Fixes request charges for offers and CreateIfNotExists APIs

### PR DESCRIPTION
**Pull request by j82w**
# Pull Request Template

## Description

This fixes bugs where the operation requires multiple requests to the service to complete one user request. This fixes offers, CreateDatabaseIfNotExists and CreateContainerIfNotExists. Tests are added to prevent future regressions. 

Added a additional check to the TransportHandler which verifies that does a warning trace if RequestChargeTracker is greater than the response. RequestChargeTracker is not used for gateway calls.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

## Closing issues

To automatically close an issue: closes #IssueNumber

### CODE REVIEW

**Review by ealsur — APPROVED** [review]
Would it make sense to add a UT on the containerCore/DatabaseCore that mocks the ClientContext and simulates scenarios like the Conflict path, and ensures the resulting RU charge is always the sum of all the mocked responses?

**Comment by j82w** [comment]
> Would it make sense to add a UT on the containerCore/DatabaseCore that mocks the ClientContext and simulates scenarios like the Conflict path, and ensures the resulting RU charge is always the sum of all the mocked responses?

This could also be done using the request handler to inject the 409.

**Comment by j82w** [comment]
> Would it make sense to add a UT on the containerCore/DatabaseCore that mocks the ClientContext and simulates scenarios like the Conflict path, and ensures the resulting RU charge is always the sum of all the mocked responses?

I added this via the handler logic in the latest iteration.

**Review by ealsur — APPROVED** [review]

**Review by FabianMeiswinkel — APPROVED** [review]
LGTM

**Pull request merged**
