### PR TITLE
[Internal] Regions: Adds new USSec Region

### PR DESCRIPTION
**Pull request by Tayham**
# Pull Request Template
## Description
Upgrades Direct package version to 3.33.1

Changes in 3.33.1

* Added `USSec West Central` region

### CODE REVIEW

**Comment by Tayham** [comment]
@microsoft-github-policy-service agree company="Microsoft"

**Comment by Tayham** [comment]
> This PR should wait until #4353 merges

That PR has now been merged and the changes are in my fork as well

**Review by kirankumarkolli — APPROVED** [review]

**Review by ealsur — APPROVED** [review]

**Pull request merged**
