### PR TITLE
Fix code sample for DocumentClient.ReadOfferAsync(String) documentation

### PR DESCRIPTION
**Pull request by sehcheese**
## Description

This is just a documentation code sample update.
- Use interpolated string instead of `string.Format`
- Fix compile errors:
  - `readResponse` is not defined, should be `response`
  - should be `response.ResponseHeaders`, not `response.Headers` on the last line
- Provide an `int` instead of a `string`, this is probably what people are interested in

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by sehcheese** [comment]
Looks like there's line ending problems. I'll try to fix that.

**Comment by sehcheese** [comment]
Hmmm... a lot of the diff is still whitespace changes. Maybe there were some lines that were in the repo wrong? @kirillg I'll let you decide what you want to do.

**Comment by j82w** [comment]
@sehcheese the DocumentClient.cs is a copy of the v2 client. The v3 client uses CosmosClient.cs. The v2 SDK isn't built using this code.

**Comment by sehcheese** [comment]
@j82w Ok, I was just trying to update the code sample at https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.documents.client.documentclient.readofferasync?view=azure-dotnet as it wasn't working for me. I don't see a `ReadOfferAsync` in CosmosClient.cs.

**Comment by j82w** [comment]
@sehcheese we didn't add offers to v3. We got feed back from most users it was very complex and confusing. We added methods off of the Database and Container to get the offer information. Check out this [sample](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/add4bef05193edc5b095f66ce90399bb263b1bc5/Microsoft.Azure.Cosmos.Samples/Usage/ContainerManagement/Program.cs#L149).

**Comment by sehcheese** [comment]
@j82w Thanks. Are there plans to add that to the published documentation on docs.microsoft.com? It's good that there are samples in the repo, but it would also be helpful to have it there.

**Comment by j82w** [comment]
@sehcheese is there a specific document you are looking at? Most of the documents should have been updated to have a v3 version. https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos?view=azure-dotnet

**Pull request closed without merging**
