### PR TITLE
Stand By Feed iterator cleanup

### PR DESCRIPTION
**Pull request by ealsur**
# Pull Request Template

## Description

The current StandByFeedIterator is checking for a scenario that no longer happens in the backend (a page size error reading the Change Feed), and this check implies a `Contains` evaluation on the failed response. We can safely remove this overhead.

### CODE REVIEW

**Comment by kirankumarkolli** [comment]
> The current StandByFeedIterator is checking for a scenario that no longer happens in the backend 
What's the new behavior?

**Comment by ealsur** [comment]
The new behavior is that the backend will return a response that fits the max payload size and not an error. 
The code here was copying a handling mechanism (reducing page size) we had in Change Feed Processor before the backend was fixed. Since the backend was fixed, this handling is not require anymore as the error it was detecting and reducing the page size, doesn't happen anymore.

**Comment by kirankumarkolli** [comment]
Is the new changes API versioned OR generic and applicable to all versions?

**Comment by ealsur** [comment]
The code removed is just dead code, that backend API already had this fix in place back at the beginning of the year. This does not leak to any of our public APIs because it was an internal retry mechanism.
The backend change feed API is not versioned.

**Pull request merged**
