### PR TITLE
CosmosClientBuilder: Fixes accountEndpoint not being set when using TokenCredential

### LINKED ISSUE #2843: Account endpoint not set when using `CosmosClientBuilder` and `TokenCredential`
**Describe the bug**
When creating `CosmosClient` using `CosmosClientBuilder` and `TokenCredential`, an error is thrown from `CosmosClient` constructor -> Message = "Value cannot be null.\r\nParameter name: uriString"

**Expected behavior**
A `CosmosClient` instance is created with no error

**Actual behavior**
An exception is thrown -> Message = "Value cannot be null.\r\nParameter name: uriString"

**Environment summary**
SDK Version: 3.22.1
OS Version Windows

### PR DESCRIPTION
**Pull request by levimatheri**
# Pull Request Template

## Description
Bug fix: AccountEndpoint was not being set when using `CosmosClientBuilder` with `TokenCredential`. Introduced in [2753](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/2753).
## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Closing issues

To automatically close an issue: closes #2843

### CODE REVIEW

**Review by ealsur — APPROVED** [review]

**Review by j82w — APPROVED** [review]

**Comment by levimatheri** [comment]
Thanks @j82w @ealsur. When would this be released?

**Comment by levimatheri** [comment]
@j82w Any info on next release? Thanks

**Comment by j82w** [comment]
The next release is currently waiting on some change to the service to be completed. Which will likely be in 2 to 3 weeks. 

Is there any reason you can't use the non-builder as a temporary workaround?

**Comment by levimatheri** [comment]
That's alright. We should be able to use the nonbuilder in the meantime.

**Pull request merged**
