### PR TITLE
[Internal] Query: Fixes LINQ Test Organization

### PR DESCRIPTION
**Pull request by leminh98**
# Pull Request Template

## Description

This PR reorganizes the LINQ test files into a folder called Linq for easier test discovery

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

## Closing issues

To automatically close an issue: closes #IssueNumber

### CODE REVIEW

**Review by adityasa — APPROVED** [review]
:shipit:

**Comment by sboshra** [comment]
> {

Should the namespace be also updated for the file move?

---
Refers to: Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Linq/LinqAggregateFunctionsBaselineTests.cs:7 in 8889c9c. [](commit_id = 8889c9ceb211e38cff5d43d763b874d10e323109, deletion_comment = False)

**Review by sboshra — APPROVED** [review]
:shipit:

**Comment by leminh98** [comment]
> > {
> 
> Should the namespace be also updated for the file move?
> 
> Refers to: Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Linq/LinqAggregateFunctionsBaselineTests.cs:7 in [8889c9c](https://github.com/Azure/azure-cosmos-dotnet-v3/commit/8889c9ceb211e38cff5d43d763b874d10e323109). [](commit_id = [8889c9c](https://github.com/Azure/azure-cosmos-dotnet-v3/commit/8889c9ceb211e38cff5d43d763b874d10e323109), deletion_comment = False)

The files are all under different namespace originally, so I haven't changed them in case there was a weird namespace dependency. I will look at that in the future

**Pull request merged**
