### PR TITLE
Add sample for using Expressions to build patch operations

### PR DESCRIPTION
**Pull request by Arithmomaniac**
## Description

Adds a sample project `Microsoft.Azure.Cosmos.Samples/Usage/StronglyTypedPatch` which contains a `StronglyTypedPatchOperationFactory`. 

This class serves a strongly-typed replacement for the `PatchOperation.` methods, allowing a path expression to be passed in instead of a string. Like other uses of expressions in the SDK, casing rules are respected, and mathematical operators and variables are inlined inside the expression.

Some examples:

```csharp
var i = 4;

StronglyTypedPatchOperationFactory<Person> factory = new(cosmosClient);

PatchOperation[] patchOperations = new[] {
    //basic and "new item" support
    factory.Add(person => person.Children[0].Children[-1], /*...*/),  //  "/children/0/children/-"
    //dictionary and escape support
    factory.Add(person => person.AlterEgos["Tilde~Man"] , /*...*/), // "/alterEgos/Tilde~0Man"
    //support for nullables
    factory.Increment(person => person.YearsWorked.Value, 1),  // "/yearsWorked"
    //support for value expression inlining
    factory.Add(person => person.Children[i- 3].Age, 25) // "/children/1/age"
};

```

Addresses the first sub-item in #2897. 

## Type of change

New feature (sample only)

### CODE REVIEW

**Comment by kirankumarkolli** [comment]
Please open once its ready

**Comment by Arithmomaniac** [comment]
It is ready

**Comment by ellern** [comment]
It would be nice if this was part of the official SDK. 
I've been using it for some time, but unfortunately it's broken with the latest 3.37.0 release.

**Comment by Arithmomaniac** [comment]
> It would be nice if this was part of the official SDK. I've been using the parts of this for some time, but unfortunately it's broken with the latest 3.37.0 release.

Can you share the error? I don't work with CosmosDB much these days, but maybe I can make a quick fix. (I'm pleased to hear this actually is being used 😁)

**Comment by ellern** [comment]
Looks like some reflection is not working correctly because of changes in the latest releases. I'm pretty confident that it was working on version 3.35.4 and maybe even on 3.36.0.

`getMemberNameDelegate = (Func<MemberInfo, CosmosLinqSerializerOptions, string>)Delegate.CreateDelegate(typeof(Func<MemberInfo, CosmosLinqSerializerOptions, string>), getMemberNameMethod);`

throws exception 
`ArgumentException: Cannot bind to the target method because its signature is not compatible with that of the delegate type.
TypeInitializationException: The type initializer for 'JsonPointerBuilder' threw an exception.

System.ArgumentException: Cannot bind to the target method because its signature is not compatible with that of the delegate type.
   at System.Delegate.CreateDelegate(Type type, MethodInfo method, Boolean throwOnBindFailure)
   at JsonPointerBuilder..cctor()
`

@Arithmomaniac is this enough or do you need more?

**Comment by Arithmomaniac** [comment]
That's enough. Thanks!

**Comment by ellern** [comment]
I took a quick look, and it looks like TypeSystem.cs has had some major changes in the GetMemberName method.

v3.36.0
https://github.com/Azure/azure-cosmos-dotnet-v3/blob/70855cb53ccce425b88551695c16853bc9903434/Microsoft.Azure.Cosmos/src/Linq/TypeSystem.cs#L25-L67

v3.37.1
https://github.com/Azure/azure-cosmos-dotnet-v3/blob/4195ec0efa5097a36e36534e140dea5afab8832e/Microsoft.Azure.Cosmos/src/Linq/TypeSystem.cs#L22-L25

**Comment by Arithmomaniac** [comment]
Yes, but if you follow through, that just means you need to do the delegate building against `DefaultCosmosLinqSerializer.SerializeMemberName`. See the LHS here:
https://github.com/Azure/azure-cosmos-dotnet-v3/commit/17bbdab53b3760664c38f95cc5edace18da4639d#diff-73919e2395e3196132f9ac6801f6f3e04de18c434342346989018c3246db2f1d

The bigger problem is that class itself is in flux (compare the LHS from 3.37.1 and the RHS from bleeding-edge); if I pushed and tested a fix targeting the latter, it wouldn't work for the former. If you follow what's going on in the code, just make the appropriate change locally.

**Comment by Arithmomaniac** [comment]
I don't, sorry. Ping me after the next SDK release and I can write one before it breaks again.

**Comment by ellern** [comment]
@Arithmomaniac here's your ping, 3.38.0 has been released

**Comment by Arithmomaniac** [comment]
@ellern Updated at https://github.com/Arithmomaniac/azure-cosmos-dotnet-v3/tree/users/avilevin/strongly-typed-patchoperations/Microsoft.Azure.Cosmos.Samples/Usage/StronglyTypedPatch . Please reach out privately if it needs to be updated again.

**Comment by ellern** [comment]
@Arithmomaniac thanks

**Pull request closed without merging**
