### PR TITLE
EnableContentResponseOnWrite documentation: Fix documentation and add samples

### LINKED ISSUE #1560: Confusing documentation for EnableContentResponseOnWrite
The [code documentation](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/0470549a9800f6ceeb23f72010e0cfb85094f1ac/Microsoft.Azure.Cosmos/src/RequestOptions/ItemRequestOptions.cs#L119) suggests that the server will not serialize back the resource to the response __if the value is true__.

However, the [usage itself](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/0470549a9800f6ceeb23f72010e0cfb85094f1ac/Microsoft.Azure.Cosmos/src/RequestOptions/ItemRequestOptions.cs#L178) suggests it has to be __false__ to not serialize the resource to the response.

Which one is it?

### PR DESCRIPTION
**Pull request by j82w**
# Pull Request Template

## Description

1. Fixed the documentation for EnableContentResponseOnWrite
2. Added sample on how to use EnableContentResponseOnWrite
3. Added read all items samples

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Closing issues

Put closes #1560, #1559

### CODE REVIEW

**Comment by Camios** [comment]
@j82w is there an automated (eg unit) test with EnableContentResponseOnWrite true vs false? Existing or planned?

The ItemRequestOptions can be passed to CreateItemAsyc method and the CreateItemStreamAsync variant (they have different response types), is that correct? The former has the ItemResponse (missing member docs) which has the Resource property representing the created item. Is there an equivalent in the stream variant’s ResponseMessage? The [example](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.container.createitemstreamasync?view=azure-dotnet#examples) talks about a ReadBodyAsync method which doesn’t exist in the member docs.
What effect does the EnableContentResponseOnWrite flag have on stream-based request responses.

**Comment by j82w** [comment]
@Camios all the tests are in [CosmosContentResponseTests](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContentResponseTests.cs#L140)

**Comment by Camios** [comment]
@j82w ah yes I did see those, but when I saw flag being set false, at the time I still understood false to mean “include created item in response”. With this PR in makes more sense. One thing though: Reading the first sentence of the summary for EnableContentResponseOnWrite, it sounds like the reverse of reality. Wording is conventionally  for when you set the true case, but in this summary it is the false case: “ Gets or sets the boolean to only return the headers and status code in the Cosmos DB response”. I think the summary should be inverted to match behaviour when is flag is true. Do I need to raise new issue for this?
And my concern about stream-based requests in prev comment?

**Comment by j82w** [comment]
If you can think of a better way to phrase it please open a new issue with the suggestion. 

The stream APIs are covered in the tests. The content will be null in those scenarios.

**Comment by ealsur** [comment]
Or even better, send a PR with your suggested text change 😄

**Pull request merged**
