### PR TITLE
Replacing CosmosResultSetIterator & CosmosQueryResponse

### PR DESCRIPTION
**Pull request by KalyanChanumolu-MSFT**
Replacing CosmosResultSetIterator & CosmosQueryResponse
# Pull Request Template

## Description

In Cosmos.Samples
Replacing CosmosResultSetIterator with CosmosFeedIterator
Replacing CosmosQueryResponse with CosmosFeedResponse/CosmosResponseMessage

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)

## Assignee

@KalyanChanumolu-MSFT

### CODE REVIEW

**Comment by KalyanChanumolu-MSFT** [comment]
@kirankumarkolli could you please review this PR

**Comment by kirankumarkolli** [comment]
@ausfeldt CI seems not making progress. Is it becoz its source branch is from external repo?

**Comment by KalyanChanumolu-MSFT** [comment]
@kirankumarkolli @ausfeldt  Any action needed from my end to get this through?

**Comment by kirankumarkolli** [comment]
Samples are now refreshed with latest 3.0.0.17-preview. Hence this PR is stale and not required.

**Comment by KalyanChanumolu-MSFT** [comment]
@kirankumarkolli The HandlerSample is still broken because it references Version=3.0.0.10 of Cosmos.Client

I can submit a PR only if it will be merged this time :)
Please let me know.

**Pull request closed without merging**
