### PR TITLE
LocalQuorum: Adds Quorum reads on Consistent Prefix Accounts

### PR DESCRIPTION
**Pull request by pravengithub**
# Pull Request Template

## Description

New Feature: Allow Strong Consistency reads (local minority reads, quorum reads from 2 replicas) for Consistent Prefix accounts. This feature can only be enabled when explicitly opting in for the consistency upgrade during the client initialization.

## Type of change

- [] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Review by kirankumarkolli — APPROVED** [review]

**Comment by pravengithub** [comment]
> @microsoft-github-policy-service agree company="Microsoft"

**Comment by ealsur** [comment]
@pravengithub Please reply without the quote `>` character

**Comment by pravengithub** [comment]
@microsoft-github-policy-service agree company="Microsoft"

**Comment by pravengithub** [comment]
> @pravengithub Please reply without the quote `>` character

@ealsur Done.

**Review by aavasthy — APPROVED** [review]

**Pull request merged**
