### PR TITLE
Client Encryption: Adds Client Encryption APIs to GA SDK

### PR DESCRIPTION
**Pull request by anujtoshniwal**
# Pull Request Template

## Description

To GA the client-encryption feature, we would need to remove the PREVIEW hooks from the SDK so that we can take the first step toward taking a dependency on the stable SDK version. 

## Type of change

Please delete options that are not relevant.

- [] New feature (non-breaking change which adds functionality)
- [] This change requires a documentation update

### CODE REVIEW

**Comment by abhijitpai** [comment]
>         [JsonProperty(PropertyName = Constants.Properties.EncryptionAlgorithmId, NullValueHandling = NullValueHandling.Ignore)]

Did we want to change this?

---
Refers to: Microsoft.Azure.Cosmos/src/Resource/ClientEncryptionKey/ClientEncryptionKeyProperties.cs:79 in e224cb8. [](commit_id = e224cb82689524d7320574f70fe747d663d4a43e, deletion_comment = False)

**Review by abhijitpai — DISMISSED** [review]
:shipit:

**Review by kr-santosh — DISMISSED** [review]

**Review by kr-santosh — COMMENTED** [review]
Anuj, was this verified by creating a private package?

**Review by abhijitpai — APPROVED** [review]
:shipit:

**Review by kr-santosh — APPROVED** [review]

**Review by kirankumarkolli — APPROVED** [review]

**Pull request merged**
