### PR TITLE
[vNext] Contract: Fix remove Spatial classes

### PR DESCRIPTION
**Pull request by ealsur**
As per API review, the Spatial classes are removed.

All the Spatial classes are basically implementations of WGS 84, that can be done by any customer and are not particular to Cosmos DB.

## Type of change

- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by kirankumarkolli** [comment]
@ealsur isn't the idea that spatial would be an extension library to core cosmos. So these types will be moved to a new library not fully remove them. 

Also we need to run it through with @sboshra, @LalithaMV .
Waiting on it.

**Comment by ealsur** [comment]
@kirankumarkolli I understood that these were just implementations of the protocol we did ourselves and anyone could do it. They could be provided by even the Azure Core team too. In any case, this removes the files from the SDK project, which is required regardless.

If we want to have a separate Nuget package we can re-add them later as part of a different project.

**Comment by ealsur** [comment]
Closing this PR as a different approach will be attempted. Shipping Spatial classes as a separate package, done in another PR.

**Comment by kirankumarkolli** [comment]
@sboshra , @bchong95 can you please take a look? (its for V4)

**Pull request closed without merging**
