### PR TITLE
Internal: Reduce usage of literal strings by using the nameof operator

### PR DESCRIPTION
**Pull request by ylabade**
# Pull Request Template

## Description

This PR contains:

- Reduce usage of literal strings by using the nameof operator
- Replace ArgumentException by ArgumentNullException when the argument is null

### CODE REVIEW

**Review by bchong95 — DISMISSED** [review]
Thanks for helping us modernize this legacy code that was written before the nameof operator was introduced!

**Review by j82w — APPROVED** [review]

**Pull request closed without merging**
