### PR TITLE
Removed unused variable

### PR DESCRIPTION
**Pull request by SeanFeldman**
## Type of change

Sample update

### CODE REVIEW

**Comment by SeanFeldman** [comment]
cc @ealsur

**Comment by SeanFeldman** [comment]
BTW, any specific reason `DeleteContainerStreamAsync()` is used instead of `DeleteContainerAsync()`?

**Comment by ealsur** [comment]
No other reason but the fact that I'm not really interested in the serialization of the response

**Comment by SeanFeldman** [comment]
> No other reason but the fact that I'm not really interested in the serialization of the response

Thank you. Just learned something from you 🙂

Sorry to pollute the PR thread, but where can I find more documentation on the API differences?

**Comment by kirankumarkolli** [comment]
@SeanFeldman thank you for your contribution.

**Pull request merged**
