### PR TITLE
Change Feed: Fixes incorrect exception messages in VersionedAndRidCheckedCompositeToken

### PR DESCRIPTION
**Pull request by ThePartyPinguin**
# Pull Request Template

## Description

During my own development I got confused due some incorrect exception message in the VersionedAndRidCheckedCompositeToken struct.

This PR fixes the exception messages to use the correct expected data type.
It also fixes an incorrect reference to the 'Version' property name in where 'Rid' should be references

## Type of change

Please delete options that are not relevant.

- [] Bug fix (non-breaking change which fixes an issue)

## Closing issues

To automatically close an issue: closes #IssueNumber

### CODE REVIEW

**Review by ealsur — APPROVED** [review]
Thank you for being proactive and avoiding others to stumble on the same problem

**Comment by ThePartyPinguin** [comment]
@ealsur No problem, happy to help

**Review by kirankumarkolli — APPROVED** [review]

**Pull request merged**
